import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from 'next/font/google'
import Sidebar from "@/components/Sidebar";

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} bg-background text-primary-text`}>
        <div className="mx-auto min-h-screen max-w-7xl px-6 py-12 md:px-12 md:py-16 lg:py-0">
          <div className="lg:flex lg:justify-between lg:gap-4">
            <Sidebar />
            <main className="text-primary-text pt-24 lg:w-[52%] lg:py-24">
              {children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
