import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from 'next/font/google'
import Sidebar from "@/components/Sidebar";

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} bg-background text-primary-text`}>
       {children}
      </body>
    </html>
  );
}
